"""Canonical implementation of the revised GBDN model families."""

from gbdn.core import (
    GraphPreprocessRecord,
    PreprocessedGraph,
    ValidatedLaplacian,
    normalized_laplacian_from_adjacency,
    preprocess_reciprocal_mean,
    require_validated_laplacian,
    validate_adjacency,
    validate_external_laplacian,
    validate_self_adjoint_operator,
    validated_normalized_laplacian,
)
from gbdn.layers import (
    ChebyshevBasis,
    GraphBlaschkeLayerMultiRoot,
    GraphBlaschkeLayerRelaxed,
    GraphBlaschkeLayerStrict,
    GraphBlaschkeLayerTight,
    normalized_laplacian,
)
from gbdn.oracle import (
    adjoint_tight_synthesis as dense_adjoint_tight_synthesis,
    apply_tight_analysis as dense_apply_tight_analysis,
    dense_chebyshev_operator,
    exact_blaschke_operator as dense_exact_blaschke_operator,
    exact_blaschke_operator_from_eigendecomposition,
    exact_blaschke_symbol as dense_exact_blaschke_symbol,
    tight_analysis_matrix as dense_tight_analysis_matrix,
)
from gbdn.model import (
    GBDNProductSum,
    GBDNRelaxed,
    GBDNStrict,
    GBDNTight,
    TightAnalysisOutput,
)
from gbdn.seed import seed_everything
from gbdn.spectral import (
    blaschke_cayley_exact,
    blaschke_cayley_symbol,
    blaschke_cheb_coeffs,
    blaschke_factor,
    blaschke_product,
    blaschke_product_cheb_coeffs,
    cayley_map,
    center_width_from_root,
    chebyshev_nodes,
    constrain_alpha,
    dct_synthesis,
    evaluate_chebyshev,
    mapped_zero_pole,
    multilevel_tight_analysis,
    multilevel_tight_synthesis,
    parameterize_center_width_roots,
    parameterize_roots,
    spectral_response,
    tight_split_responses,
)

__all__ = [
    "GBDNStrict",
    "GBDNTight",
    "GBDNProductSum",
    "GBDNRelaxed",
    "TightAnalysisOutput",
    "GraphPreprocessRecord",
    "PreprocessedGraph",
    "ValidatedLaplacian",
    "validate_adjacency",
    "validate_self_adjoint_operator",
    "validated_normalized_laplacian",
    "normalized_laplacian_from_adjacency",
    "preprocess_reciprocal_mean",
    "require_validated_laplacian",
    "validate_external_laplacian",
    "ChebyshevBasis",
    "GraphBlaschkeLayerStrict",
    "GraphBlaschkeLayerMultiRoot",
    "GraphBlaschkeLayerTight",
    "GraphBlaschkeLayerRelaxed",
    "normalized_laplacian",
    "dense_exact_blaschke_symbol",
    "dense_exact_blaschke_operator",
    "exact_blaschke_operator_from_eigendecomposition",
    "dense_chebyshev_operator",
    "dense_tight_analysis_matrix",
    "dense_apply_tight_analysis",
    "dense_adjoint_tight_synthesis",
    "blaschke_cayley_exact",
    "blaschke_cayley_symbol",
    "blaschke_cheb_coeffs",
    "blaschke_product_cheb_coeffs",
    "blaschke_factor",
    "blaschke_product",
    "cayley_map",
    "center_width_from_root",
    "chebyshev_nodes",
    "dct_synthesis",
    "constrain_alpha",
    "parameterize_roots",
    "parameterize_center_width_roots",
    "mapped_zero_pole",
    "evaluate_chebyshev",
    "multilevel_tight_analysis",
    "multilevel_tight_synthesis",
    "spectral_response",
    "tight_split_responses",
    "seed_everything",
]
